const express = require("express");
const router = express.Router();
const pool = require("../db/connection");
const PDFDocument = require("pdfkit");

// GET /api/report/logs
// Export all attack logs as PDF
router.get("/logs", async (req, res) => {
  try {
    console.log("[report] Exporting all attack logs as PDF...");
    const logsResult = await pool.query(`
      SELECT id, timestamp, source_ip, method, path, attack_type, severity, response_code
      FROM attack_logs
      ORDER BY timestamp DESC
      LIMIT 100
    `);

    const logs = logsResult.rows;

    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
      bufferPages: true
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'attachment; filename="attack-logs-report.pdf"');

    doc.pipe(res);

    const primaryColor = "#0d1117";
    const accentColor = "#388bfd";
    const mutedColor = "#8b949e";

    // Header
    doc.fillColor(primaryColor).rect(0, 0, 595.28, 90).fill();
    doc.fillColor("#ffffff").fontSize(20).font("Helvetica-Bold").text("ATTACK LOGS SUMMARY REPORT", 40, 25);
    doc.fillColor(accentColor).fontSize(10).font("Helvetica-Bold").text("SecureBank SOC Platform Telemetry", 40, 50);
    doc.fillColor(mutedColor).fontSize(9).font("Helvetica").text(`Generated: ${new Date().toUTCString()}`, 40, 65);
    doc.fillColor("#f85149").fontSize(10).font("Helvetica-Bold").text("CLASSIFICATION: RESTRICTED", 420, 25, { align: "right" });
    doc.fillColor("#ffffff").fontSize(9).font("Helvetica").text(`Total Logs: ${logs.length}`, 420, 40, { align: "right" });
    
    doc.y = 110;

    const tableData = [
      ["Time", "Source IP", "Method", "Path", "Attack", "Sev", "Code"],
      ...logs.map(log => [
        new Date(log.timestamp).toLocaleTimeString(),
        String(log.source_ip),
        String(log.method),
        String(log.path).substring(0, 30) + (String(log.path).length > 30 ? "..." : ""),
        String(log.attack_type || "recon"),
        String(log.severity),
        String(log.response_code)
      ])
    ];

    const colWidths = [60, 85, 45, 165, 70, 40, 50];
    const rowHeight = 20;
    doc.fontSize(8);
    
    let currentY = doc.y;
    doc.fillColor("#161b22").rect(40, currentY, 515, rowHeight).fill();
    doc.fillColor("#388bfd").font("Helvetica-Bold");
    let currentX = 40;
    tableData[0].forEach((headerText, colIdx) => {
      doc.text(headerText, currentX + 5, currentY + 6, { width: colWidths[colIdx] - 10 });
      currentX += colWidths[colIdx];
    });
    currentY += rowHeight;

    doc.font("Helvetica");
    for (let rowIdx = 1; rowIdx < tableData.length; rowIdx++) {
      if (currentY > 750) {
        doc.addPage();
        doc.fillColor(primaryColor).rect(0, 0, 595.28, 45).fill();
        doc.fillColor("#ffffff").fontSize(12).font("Helvetica-Bold").text("ATTACK LOGS SUMMARY REPORT", 40, 16);
        
        currentY = 70;
        doc.fillColor("#161b22").rect(40, currentY, 515, rowHeight).fill();
        doc.fillColor("#388bfd").font("Helvetica-Bold").fontSize(8);
        currentX = 40;
        tableData[0].forEach((headerText, colIdx) => {
          doc.text(headerText, currentX + 5, currentY + 6, { width: colWidths[colIdx] - 10 });
          currentX += colWidths[colIdx];
        });
        currentY += rowHeight;
        doc.font("Helvetica");
      }

      if (rowIdx % 2 === 0) {
        doc.fillColor("#0f1620").rect(40, currentY, 515, rowHeight).fill();
      }
      doc.fillColor("rgba(56, 139, 253, 0.15)").rect(40, currentY + rowHeight - 0.5, 515, 0.5).fill();

      doc.fillColor("#ffffff");
      currentX = 40;
      tableData[rowIdx].forEach((cellText, colIdx) => {
        doc.text(cellText || "", currentX + 5, currentY + 6, { width: colWidths[colIdx] - 10 });
        currentX += colWidths[colIdx];
      });
      currentY += rowHeight;
    }

    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fillColor(mutedColor).fontSize(8).font("Helvetica");
      doc.text("Generated by SecureBank SOC Platform", 40, 800);
      doc.text(`Page ${i + 1} of ${pageCount}`, 40, 800, { align: "right", width: 515 });
    }

    doc.end();
  } catch (err) {
    console.error("[report logs] Error:", err.message);
    res.status(500).json({ success: false, error: "Failed to generate logs report" });
  }
});

// GET /api/report/profiles
// Export all attacker profiles as PDF
router.get("/profiles", async (req, res) => {
  try {
    console.log("[report] Exporting all attacker profiles as PDF...");
    const profilesResult = await pool.query(`
      SELECT ip, country, city, isp, threat_score, total_requests, last_seen
      FROM attacker_profiles
      ORDER BY threat_score DESC
      LIMIT 100
    `);

    const profiles = profilesResult.rows;

    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
      bufferPages: true
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'attachment; filename="attacker-profiles-report.pdf"');

    doc.pipe(res);

    const primaryColor = "#0d1117";
    const accentColor = "#388bfd";
    const mutedColor = "#8b949e";

    // Header
    doc.fillColor(primaryColor).rect(0, 0, 595.28, 90).fill();
    doc.fillColor("#ffffff").fontSize(20).font("Helvetica-Bold").text("ATTACKER PROFILES REPORT", 40, 25);
    doc.fillColor(accentColor).fontSize(10).font("Helvetica-Bold").text("SecureBank SOC Platform Telemetry", 40, 50);
    doc.fillColor(mutedColor).fontSize(9).font("Helvetica").text(`Generated: ${new Date().toUTCString()}`, 40, 65);
    doc.fillColor("#f85149").fontSize(10).font("Helvetica-Bold").text("CLASSIFICATION: RESTRICTED", 420, 25, { align: "right" });
    doc.fillColor("#ffffff").fontSize(9).font("Helvetica").text(`Total Profiles: ${profiles.length}`, 420, 40, { align: "right" });
    
    doc.y = 110;

    const tableData = [
      ["IP Address", "Location", "ISP", "Threat Score", "Total Req", "Last Seen"],
      ...profiles.map(p => {
        let threatLevel = "LOW";
        if (p.threat_score >= 80) threatLevel = "CRITICAL";
        else if (p.threat_score >= 60) threatLevel = "HIGH";
        else if (p.threat_score >= 40) threatLevel = "MEDIUM";
        
        return [
          String(p.ip),
          `${p.country || "Unknown"} / ${p.city || "Unknown"}`,
          String(p.isp || "Unknown").substring(0, 25) + (String(p.isp || "").length > 25 ? "..." : ""),
          `${p.threat_score}/100 [${threatLevel}]`,
          String(p.total_requests),
          new Date(p.last_seen).toLocaleDateString()
        ];
      })
    ];

    const colWidths = [105, 115, 135, 80, 40, 40];
    const rowHeight = 20;
    doc.fontSize(8);
    
    let currentY = doc.y;
    doc.fillColor("#161b22").rect(40, currentY, 515, rowHeight).fill();
    doc.fillColor("#388bfd").font("Helvetica-Bold");
    let currentX = 40;
    tableData[0].forEach((headerText, colIdx) => {
      doc.text(headerText, currentX + 5, currentY + 6, { width: colWidths[colIdx] - 10 });
      currentX += colWidths[colIdx];
    });
    currentY += rowHeight;

    doc.font("Helvetica");
    for (let rowIdx = 1; rowIdx < tableData.length; rowIdx++) {
      if (currentY > 750) {
        doc.addPage();
        doc.fillColor(primaryColor).rect(0, 0, 595.28, 45).fill();
        doc.fillColor("#ffffff").fontSize(12).font("Helvetica-Bold").text("ATTACKER PROFILES REPORT", 40, 16);
        
        currentY = 70;
        doc.fillColor("#161b22").rect(40, currentY, 515, rowHeight).fill();
        doc.fillColor("#388bfd").font("Helvetica-Bold").fontSize(8);
        currentX = 40;
        tableData[0].forEach((headerText, colIdx) => {
          doc.text(headerText, currentX + 5, currentY + 6, { width: colWidths[colIdx] - 10 });
          currentX += colWidths[colIdx];
        });
        currentY += rowHeight;
        doc.font("Helvetica");
      }

      if (rowIdx % 2 === 0) {
        doc.fillColor("#0f1620").rect(40, currentY, 515, rowHeight).fill();
      }
      doc.fillColor("rgba(56, 139, 253, 0.15)").rect(40, currentY + rowHeight - 0.5, 515, 0.5).fill();

      doc.fillColor("#ffffff");
      currentX = 40;
      tableData[rowIdx].forEach((cellText, colIdx) => {
        doc.text(cellText || "", currentX + 5, currentY + 6, { width: colWidths[colIdx] - 10 });
        currentX += colWidths[colIdx];
      });
      currentY += rowHeight;
    }

    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fillColor(mutedColor).fontSize(8).font("Helvetica");
      doc.text("Generated by SecureBank SOC Platform", 40, 800);
      doc.text(`Page ${i + 1} of ${pageCount}`, 40, 800, { align: "right", width: 515 });
    }

    doc.end();
  } catch (err) {
    console.error("[report profiles] Error:", err.message);
    res.status(500).json({ success: false, error: "Failed to generate profiles report" });
  }
});

// GET /api/report/:ip
// Generate a professional incident report as PDF
router.get("/:ip", async (req, res) => {

  try {
    const { ip } = req.params;

    // Run queries in parallel
    const [profileResult, eventsResult, tokensResult, tokenAlertsResult] = await Promise.all([
      pool.query("SELECT * FROM attacker_profiles WHERE ip = $1", [ip]),
      pool.query("SELECT * FROM attack_logs WHERE source_ip = $1 ORDER BY timestamp DESC LIMIT 20", [ip]),
      pool.query("SELECT * FROM honeytokens WHERE attacker_ip = $1", [ip]),
      pool.query("SELECT * FROM honeytoken_alerts WHERE attacker_ip = $1", [ip]),
    ]);

    if (profileResult.rows.length === 0) {
      return res.status(404).json({ success: false, error: "Attacker profile not found" });
    }

    const profile = profileResult.rows[0];
    const events = eventsResult.rows;
    const tokens = tokensResult.rows;
    const tokenAlerts = tokenAlertsResult.rows;

    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
      bufferPages: true // Allows dynamic page numbering in footer
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="threat-report-${ip}.pdf"`);

    doc.pipe(res);

    // --- COLOR PALETTE ---
    const primaryColor = "#0d1117";
    const accentColor = "#388bfd";
    const mutedColor = "#8b949e";
    const lightBg = "#161b22";
    const borderColor = "rgba(56, 139, 253, 0.15)";
    
    const severityColors = {
      CRITICAL: "#f85149",
      HIGH: "#db6d28",
      MEDIUM: "#e3b341",
      LOW: "#39d353"
    };

    // Get Risk Level Label
    const threatScore = profile.threat_score;
    let threatLevel = "LOW";
    if (threatScore >= 80) threatLevel = "CRITICAL";
    else if (threatScore >= 60) threatLevel = "HIGH";
    else if (threatScore >= 40) threatLevel = "MEDIUM";
    const threatColor = severityColors[threatLevel];

    // --- 1. HEADER ---
    doc.fillColor(primaryColor).rect(0, 0, 595.28, 90).fill(); // Navy base band
    doc.fillColor("#ffffff").fontSize(20).font("Helvetica-Bold").text("THREAT INTELLIGENCE REPORT", 40, 25);
    doc.fillColor(accentColor).fontSize(10).font("Helvetica-Bold").text("SecureBank SOC Incident Response", 40, 50);
    doc.fillColor(mutedColor).fontSize(9).font("Helvetica").text(`Generated: ${new Date().toUTCString()}`, 40, 65);
    doc.fillColor("#f85149").fontSize(10).font("Helvetica-Bold").text("CLASSIFICATION: CONFIDENTIAL", 420, 25, { align: "right" });
    doc.fillColor("#ffffff").fontSize(9).font("Helvetica").text(`Target IP: ${ip}`, 420, 40, { align: "right" });
    doc.y = 110;

    // --- 2. EXECUTIVE SUMMARY (Box with light background) ---
    doc.fillColor(lightBg).rect(40, doc.y, 515, 110).fill();
    doc.fillColor("#388bfd").fontSize(11).font("Helvetica-Bold").text("1. EXECUTIVE SUMMARY", 50, doc.y + 10);
    
    // Summary details
    doc.fillColor("#ffffff").fontSize(9).font("Helvetica");
    doc.text(`Attacker IP: ${ip}`, 55, doc.y + 15);
    doc.text(`Country: ${profile.country || "Unknown"} / ${profile.city || "Unknown"}`, 55, doc.y + 30);
    doc.text(`ISP/Provider: ${profile.isp || "Unknown"}`, 55, doc.y + 45);
    
    doc.text(`First Seen: ${new Date(profile.first_seen).toUTCString()}`, 275, doc.y + 15);
    doc.text(`Last Seen: ${new Date(profile.last_seen).toUTCString()}`, 275, doc.y + 30);
    doc.text(`Total Requests: ${profile.total_requests}`, 275, doc.y + 45);
    
    doc.fillColor(threatColor).fontSize(10).font("Helvetica-Bold").text(`Overall Threat Level: ${threatLevel}`, 55, doc.y + 80);
    
    doc.y = doc.y + 130;

    // --- 3. THREAT SCORE CARD ---
    doc.fillColor(borderColor).rect(40, doc.y, 515, 60).stroke();
    doc.fillColor(threatColor).fontSize(28).font("Helvetica-Bold").text(`${threatScore}`, 60, doc.y + 10);
    doc.fillColor(mutedColor).fontSize(10).font("Helvetica").text("/ 100", 110, doc.y + 25);
    
    doc.fillColor("#ffffff").fontSize(11).font("Helvetica-Bold").text(`Threat Level: ${threatLevel}`, 160, doc.y + 12);
    let scoreDesc = "Attacker exhibits passive scanning or minor reconnaissance.";
    if (threatLevel === "CRITICAL") scoreDesc = "Attacker is performing direct, high-impact exploits and triggering active deception traps.";
    else if (threatLevel === "HIGH") scoreDesc = "Attacker is actively running persistent penetration tools targeting user databases.";
    else if (threatLevel === "MEDIUM") scoreDesc = "Attacker is submitting automated brute-force attacks and parameter injection.";
    doc.fillColor(mutedColor).fontSize(9).font("Helvetica").text(scoreDesc, 160, doc.y + 28, { width: 380 });
    
    doc.y = doc.y + 80;

    // --- 4. ATTACK BREAKDOWN ---
    doc.fillColor("#388bfd").fontSize(11).font("Helvetica-Bold").text("2. ATTACK BREAKDOWN", 40, doc.y);
    doc.y = doc.y + 15;

    const breakdownTable = [
      ["Exploit Vector", "Telemetry Count"],
      ["SQL Injection", String(profile.sqli_count || 0)],
      ["Cross-Site Scripting (XSS)", String(profile.xss_count || 0)],
      ["Brute Force Credentials", String(profile.bruteforce_count || 0)],
      ["Directory Traversal", String(profile.traversal_count || 0)],
      ["CSRF Attempts", String(profile.csrf_count || 0)],
      ["IDOR Manipulation", String(profile.idor_count || 0)]
    ];

    drawTable(doc, breakdownTable, 40, doc.y, [280, 235]);
    doc.y = doc.y + 160;

    // --- 5. ATTACK TIMELINE (Last 20 events) ---
    doc.addPage();
    // Band header for other pages
    doc.fillColor(primaryColor).rect(0, 0, 595.28, 45).fill();
    doc.fillColor("#ffffff").fontSize(12).font("Helvetica-Bold").text("THREAT REPORT: DETAILED TELEMETRY", 40, 16);
    doc.y = 70;

    doc.fillColor("#388bfd").fontSize(11).font("Helvetica-Bold").text("3. DETAILED EVENT FEED (LAST 20 EVENTS)", 40, doc.y);
    doc.y = doc.y + 20;

    if (events.length === 0) {
      doc.fillColor(mutedColor).fontSize(9).font("Helvetica").text("No recent events logged.", 45, doc.y);
      doc.y = doc.y + 20;
    } else {
      doc.fontSize(8).font("Helvetica");
      events.forEach((event, idx) => {
        if (doc.y > 750) {
          doc.addPage();
          doc.fillColor(primaryColor).rect(0, 0, 595.28, 45).fill();
          doc.fillColor("#ffffff").fontSize(12).font("Helvetica-Bold").text("THREAT REPORT: DETAILED TELEMETRY", 40, 16);
          doc.y = 70;
        }

        const dateStr = new Date(event.timestamp).toLocaleTimeString();
        const payloadSnippet = event.payload ? event.payload.replace(/\n/g, " ").substring(0, 80) : "N/A";
        const severityLabel = event.severity_label || "LOW";
        
        doc.fillColor("#ffffff").text(`[${dateStr}]`, 40, doc.y, { continued: true });
        doc.fillColor(accentColor).text(` ${event.method} `, { continued: true });
        doc.fillColor("#ffffff").text(`${event.path} `, { continued: true });
        doc.fillColor(severityColors[severityLabel] || mutedColor).text(`[${severityLabel}]`, { continued: true });
        doc.fillColor(mutedColor).text(` — ${payloadSnippet}`, { width: 515 });
        doc.y = doc.y + 13;
      });
    }

    doc.y = doc.y + 15;

    // --- 6. INDICATORS OF COMPROMISE (IOCs) ---
    if (doc.y > 600) {
      doc.addPage();
      doc.fillColor(primaryColor).rect(0, 0, 595.28, 45).fill();
      doc.fillColor("#ffffff").fontSize(12).font("Helvetica-Bold").text("THREAT REPORT: DETAILED TELEMETRY", 40, 16);
      doc.y = 70;
    }

    doc.fillColor("#388bfd").fontSize(11).font("Helvetica-Bold").text("4. INDICATORS OF COMPROMISE (IOCs)", 40, doc.y);
    doc.y = doc.y + 15;

    // List out tools and client details
    doc.fillColor("#ffffff").fontSize(9).font("Helvetica");
    doc.text(`• Identified Tool Signature: ${profile.tool || "Generic script/manual request"}`, 50, doc.y);
    doc.text(`• User-Agent / OS Fingerprint: ${profile.os || "Unknown OS"}`, 50, doc.y + 15);
    
    // Unique paths and payloads
    const uniquePaths = [...new Set(events.map(e => e.path))].slice(0, 5);
    doc.text(`• Target Endpoints Sampled:`, 50, doc.y + 30);
    uniquePaths.forEach((path, idx) => {
      doc.text(`   - ${path}`, 60, doc.y + 45 + (idx * 12));
    });

    const startFlagsY = doc.y + 50 + (uniquePaths.length * 12);
    doc.text(`• Security Flag Identifiers:`, 50, startFlagsY);
    doc.text(`   - Attempted Account Takeover (ATO): ${profile.attempted_account_takeover ? "YES" : "NO"}`, 60, startFlagsY + 15);
    doc.text(`   - Attempted Funds Transfer: ${profile.attempted_funds_transfer ? "YES" : "NO"}`, 60, startFlagsY + 27);
    doc.text(`   - Privilege Escalation Probe: ${profile.attempted_privilege_escalation ? "YES" : "NO"}`, 60, startFlagsY + 39);

    doc.y = startFlagsY + 60;

    // --- 7. HONEYTOKEN ACTIVITY ---
    if (doc.y > 620) {
      doc.addPage();
      doc.fillColor(primaryColor).rect(0, 0, 595.28, 45).fill();
      doc.fillColor("#ffffff").fontSize(12).font("Helvetica-Bold").text("THREAT REPORT: DETAILED TELEMETRY", 40, 16);
      doc.y = 70;
    }

    doc.fillColor("#388bfd").fontSize(11).font("Helvetica-Bold").text("5. HONEYTOKEN & DECEPTION LOGS", 40, doc.y);
    doc.y = doc.y + 15;

    if (tokens.length === 0 && tokenAlerts.length === 0) {
      doc.fillColor(mutedColor).fontSize(9).font("Helvetica").text("No deception assets or honeytoken triggers associated with this attacker.", 50, doc.y);
      doc.y = doc.y + 20;
    } else {
      doc.fillColor("#ffffff").fontSize(9).font("Helvetica");
      doc.text(`Deception Assets Planted: ${tokens.length} token(s)`, 50, doc.y);
      doc.text(`Triggered Deception Alerts: ${tokenAlerts.length} alert(s)`, 50, doc.y + 15);
      doc.y = doc.y + 35;

      if (tokenAlerts.length > 0) {
        const honeytokenTable = [
          ["Token ID", "Type", "Triggered At", "Severity"],
          ...tokenAlerts.map(ta => {
            const tk = tokens.find(t => t.id === ta.honeytoken_id) || { type: "Unknown" };
            return [
              String(ta.honeytoken_id).substring(0, 8) + "...",
              String(tk.type),
              new Date(ta.triggered_at).toLocaleTimeString(),
              String(ta.severity)
            ];
          })
        ];
        drawTable(doc, honeytokenTable, 40, doc.y, [120, 120, 150, 125]);
        doc.y = doc.y + 60 + (tokenAlerts.length * 20);
      }
    }

    // --- 8. RISK ASSESSMENT (Dynamic based on attack types) ---
    if (doc.y > 550) {
      doc.addPage();
      doc.fillColor(primaryColor).rect(0, 0, 595.28, 45).fill();
      doc.fillColor("#ffffff").fontSize(12).font("Helvetica-Bold").text("THREAT REPORT: DETAILED TELEMETRY", 40, 16);
      doc.y = 70;
    }

    doc.fillColor("#388bfd").fontSize(11).font("Helvetica-Bold").text("6. SECURITY RISK ASSESSMENT", 40, doc.y);
    doc.y = doc.y + 15;

    const hasSqli = (profile.sqli_count || 0) > 0;
    const hasXss = (profile.xss_count || 0) > 0;
    const hasBruteforce = (profile.bruteforce_count || 0) > 0;
    const hasTraversal = (profile.traversal_count || 0) > 0;

    let riskAssessmentText = "";
    if (hasSqli) {
      riskAssessmentText += "SQL Injection (SQLi) attempts indicate that the attacker is trying to bypass database layer controls. If successful, this can lead to full database exfiltration, credential leakage, and potential backend database host takeover. The threat level is heightened due to the targeted database-probing behaviors.\n\n";
    }
    if (hasBruteforce) {
      riskAssessmentText += "Brute Force attempts suggest active efforts to perform account takeover against employees or customers. This indicates a high level of threat regarding authentication system compromises, key stuffing, or brute force credential discovery.\n\n";
    }
    if (hasTraversal) {
      riskAssessmentText += "Directory Traversal attempts indicate that the attacker is probing the system for path exposure, configuration file leakage, or arbitrary file reads. This can expose sensitive host system configurations or API keys stored in local environment directories.\n\n";
    }
    if (hasXss) {
      riskAssessmentText += "Cross-Site Scripting (XSS) payload delivery indicates that the attacker attempts to perform client-side hijacking, session steal attempts, or phishing redirects targeting active users of the banking application.\n\n";
    }
    if (!riskAssessmentText) {
      riskAssessmentText = "The system has logged general scanning and probing actions. While no high-impact exploits were successfully validated, the persistent recon patterns pose a low-to-medium risk of future targeted exploitation if security patches are not applied.\n";
    }

    doc.fillColor("#ffffff").fontSize(9).font("Helvetica").text(riskAssessmentText, 50, doc.y, { width: 505 });
    doc.y = doc.y + 100;

    // --- 9. RECOMMENDATIONS ---
    if (doc.y > 600) {
      doc.addPage();
      doc.fillColor(primaryColor).rect(0, 0, 595.28, 45).fill();
      doc.fillColor("#ffffff").fontSize(12).font("Helvetica-Bold").text("THREAT REPORT: DETAILED TELEMETRY", 40, 16);
      doc.y = 70;
    }

    doc.fillColor("#388bfd").fontSize(11).font("Helvetica-Bold").text("7. ACTIONS & REMEDIATION RECOMMENDATIONS", 40, doc.y);
    doc.y = doc.y + 15;

    const recommendations = [];
    if (hasSqli) {
      recommendations.push("Implement strictly parameterised queries and prepared statements across all database interfaces.");
      recommendations.push("Review database access controls and enforce the principle of least privilege.");
    }
    if (hasXss) {
      recommendations.push("Implement strict Content Security Policy (CSP) headers and escape all dynamic user outputs.");
      recommendations.push("Set HttpOnly and Secure flags on all session cookies to mitigate session theft.");
    }
    if (hasBruteforce) {
      recommendations.push("Enforce account lockout policies after 5 failed authentication attempts.");
      recommendations.push("Enforce Multi-Factor Authentication (MFA) for administrative and user portals.");
    }
    if (hasTraversal) {
      recommendations.push("Apply strict input validation on file download endpoints to whitelist allowed files.");
      recommendations.push("Run the application services in a restricted directory jail (e.g. chroot, container isolate).");
    }
    recommendations.push("Deploy a Web Application Firewall (WAF) to filter out automated exploit scripts.");
    recommendations.push("Block the malicious IP at the edge firewall level and report to AbuseIPDB.");

    doc.fillColor("#ffffff").fontSize(9).font("Helvetica");
    recommendations.forEach((rec, idx) => {
      doc.text(`${idx + 1}. ${rec}`, 50, doc.y + (idx * 15), { width: 500 });
    });

    // --- 10. DYNAMIC FOOTER & PAGE NUMBERS ---
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fillColor(mutedColor).fontSize(8).font("Helvetica");
      doc.text("Generated by SecureBank SOC Platform", 40, 800);
      doc.text(`Page ${i + 1} of ${pageCount}`, 40, 800, { align: "right", width: 515 });
    }

    doc.end();
  } catch (err) {
    console.error("[report] Error:", err.message);
    res.status(500).json({ success: false, error: "Failed to generate report" });
  }
});

// Helper function to draw table in PDF
function drawTable(doc, data, x, y, colWidths) {
  const rowHeight = 18;
  const fontSize = 8.5;
  doc.fontSize(fontSize);

  // Draw header row
  const totalWidth = colWidths.reduce((a, b) => a + b, 0);
  doc.fillColor("#161b22").rect(x, y, totalWidth, rowHeight).fill();
  doc.fillColor("#388bfd").font("Helvetica-Bold");
  
  let currentX = x;
  data[0].forEach((headerText, colIdx) => {
    doc.text(headerText, currentX + 6, y + 4, { width: colWidths[colIdx] - 12 });
    currentX += colWidths[colIdx];
  });

  // Draw data rows
  doc.font("Helvetica");
  let currentY = y + rowHeight;
  for (let rowIdx = 1; rowIdx < data.length; rowIdx++) {
    // Alternate backgrounds
    if (rowIdx % 2 === 0) {
      doc.fillColor("#0f1620").rect(x, currentY, totalWidth, rowHeight).fill();
    }
    
    doc.fillColor("#8b949e").rect(x, currentY + rowHeight - 0.5, totalWidth, 0.5).fill(); // border line

    doc.fillColor("#ffffff");
    currentX = x;
    data[rowIdx].forEach((cellText, colIdx) => {
      doc.text(cellText || "", currentX + 6, currentY + 4, { width: colWidths[colIdx] - 12 });
      currentX += colWidths[colIdx];
    });
    currentY += rowHeight;
  }
}

module.exports = router;
